#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <hello_flipper_ui_icons.h>

static void hello_flipper_ui_draw_callback(Canvas* canvas, void* context) {
    UNUSED(context);

    // Clear the canvas
    canvas_clear(canvas);

    // Set a primary font
    canvas_set_font(canvas, FontPrimary);

    // Drawing a simple hello world text
    canvas_draw_str_aligned(canvas, 64, 32, AlignCenter, AlignCenter, "Hello, Flipper!");
}

static void hello_flipper_ui_input_callback(InputEvent* event, void* context) {
    FuriMessageQueue* queue = context;
    furi_message_queue_put(queue, event, FuriWaitForever);
}

int32_t hello_flipper_ui_app(void* p) {
    UNUSED(p);

    // Allocate the ViewPort
    ViewPort* view_port = view_port_alloc();
    // Allocate a message queue for input events
    FuriMessageQueue* queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    // Set the draw and input callbacks for the ViewPort
    view_port_draw_callback_set(view_port, hello_flipper_ui_draw_callback, NULL);
    view_port_input_callback_set(view_port, hello_flipper_ui_input_callback, queue);

    // Get a reference to the GUI and add the ViewPort to it
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    InputEvent event;
    bool keep_running = true;
    while(keep_running) {
        // Wait for an input event
        if(furi_message_queue_get(queue, &event, FuriWaitForever) == FuriStatusOk) {
            // Check for the back button press to exit the application
            if(event.type == InputTypePress && event.key == InputKeyBack) {
                keep_running = false;
            }
        } else {
            // If we failed to get a message from a queue, we exit the loop
            keep_running = false;
        }
    }

    // When our application is done, we should disable the viewport and free the allocated resources
    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);

    furi_message_queue_free(queue);
    furi_record_close(RECORD_GUI);

    return 0;
}
